/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.ui.data.lib;

import com.db.model.lib.RatingKepentinganModel;
import com.db.model.lib.SiswaModel;
import com.ui.form.lib.Add_RatingKepentingan;
import static com.ui.lib.Index.pb_main;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author WILDAN
 */
public class Data_Siswa extends javax.swing.JFrame {

    /**
     * Creates new form Siswa
     */
    
    DefaultTableModel model;
    SiswaModel siswaModel = new SiswaModel();
    public Data_Siswa() {
        initComponents();
        siswaModel.setTableModel(siswa);
        loadData(pb_main);
        timer.start();
        
        setTextPopMenu();
        siswa.setAutoCreateRowSorter(true);
    }
    
    public static int countData = 50;
    public static Timer timer;
    public static int size;
    public static int time;
    
    private void loadData(JProgressBar pb) {
        size = countData;
        timer = new Timer(size, new ActionListener() {
        
            public void actionPerformed(ActionEvent evt) {
                time++;
                pb.setValue(time);
                pb.setStringPainted(true);
                    
                
                
                if(pb.getPercentComplete() == 1) {
                    timer.stop();
                    pb.setValue(0);
                    pb.setString("");
                }else if(time <= 30) {
                    if(time == 10) pb.setString("Checking.");
                    if(time == 20) pb.setString("Checking..");
                    if(time == 30) pb.setString("Checking...");
                    siswaModel.refreshData();
                }else if(time == 51) {
                    timer.stop();
                    siswaModel.getAllData();
                    timer.start();
                }else {
                    if(time == 50) pb.setString("Download.");
                    if(time == 60) pb.setString("Download..");
                    if(time == 70) pb.setString("Download...");
                }
            }
                
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popMenu_siswa = new javax.swing.JPopupMenu();
        popMenuItem_edit = new javax.swing.JMenuItem();
        popMenuItem_delete = new javax.swing.JMenuItem();
        popMenuItem_settingKriteria = new javax.swing.JMenuItem();
        popMenu_siswaRatingKepentingan = new javax.swing.JMenu();
        popMenuItem_showRatingKepentingan = new javax.swing.JMenuItem();
        popMenuItem_addRatingKepentingan = new javax.swing.JMenuItem();
        jsp_siswa = new javax.swing.JScrollPane();
        siswa = new javax.swing.JTable();

        popMenuItem_edit.setText("jMenuItem1");
        popMenuItem_edit.setEnabled(false);
        popMenu_siswa.add(popMenuItem_edit);

        popMenuItem_delete.setText("jMenuItem1");
        popMenuItem_delete.setEnabled(false);
        popMenu_siswa.add(popMenuItem_delete);

        popMenuItem_settingKriteria.setText("jMenuItem1");
        popMenuItem_settingKriteria.setEnabled(false);
        popMenu_siswa.add(popMenuItem_settingKriteria);

        popMenu_siswaRatingKepentingan.setText("jMenu1");

        popMenuItem_showRatingKepentingan.setText("jMenuItem1");
        popMenuItem_showRatingKepentingan.setEnabled(false);
        popMenuItem_showRatingKepentingan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popMenuItem_showRatingKepentinganActionPerformed(evt);
            }
        });
        popMenu_siswaRatingKepentingan.add(popMenuItem_showRatingKepentingan);

        popMenuItem_addRatingKepentingan.setText("jMenuItem1");
        popMenuItem_addRatingKepentingan.setEnabled(false);
        popMenuItem_addRatingKepentingan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popMenuItem_addRatingKepentinganActionPerformed(evt);
            }
        });
        popMenu_siswaRatingKepentingan.add(popMenuItem_addRatingKepentingan);

        popMenu_siswa.add(popMenu_siswaRatingKepentingan);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        siswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        siswa.setComponentPopupMenu(popMenu_siswa);
        siswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                siswaMouseClicked(evt);
            }
        });
        jsp_siswa.setViewportView(siswa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jsp_siswa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jsp_siswa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setTextPopMenu() {
        popMenuItem_edit.setText("Edit");
        popMenuItem_delete.setText("Delete");
        popMenuItem_settingKriteria.setText("Setting Kriteria");
        popMenuItem_showRatingKepentingan.setText("Show Rating Kepentingan");
        popMenuItem_addRatingKepentingan.setText("Add Rating Kepentingan");
        popMenu_siswaRatingKepentingan.setText("Rating Kepentingan");
    }
    
    private void siswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siswaMouseClicked
        // TODO add your handling code here:
        if(siswa.getSelectedRowCount() == 1) {
            popMenuItem_edit.setEnabled(true);
            popMenuItem_edit.setText("Edit");
            popMenuItem_delete.setEnabled(true);
            popMenuItem_delete.setText("Delete");
            popMenuItem_settingKriteria.setEnabled(true);
            popMenuItem_settingKriteria.setText("Setting Kriteria");
            
            popMenu_siswaRatingKepentingan.setEnabled(true);
            popMenu_siswaRatingKepentingan.setText("Rating Kepentingan");
            
            popMenuItem_showRatingKepentingan.setText("Show Rating Kepentingan");
            popMenuItem_showRatingKepentingan.setEnabled(true);
            popMenuItem_addRatingKepentingan.setText("Add Rating Kepentingan");
            popMenuItem_addRatingKepentingan.setEnabled(true);
            if(!siswa.getValueAt(siswa.getSelectedRow(), 0).equals("")) {

            }
        }else if(siswa.getSelectedRowCount() > 1) {
            popMenuItem_delete.setEnabled(true);
            popMenuItem_edit.setEnabled(false);
            popMenuItem_settingKriteria.setEnabled(false);
            popMenuItem_showRatingKepentingan.setEnabled(false);
            popMenu_siswaRatingKepentingan.setEnabled(false);
            popMenu_siswaRatingKepentingan.setText("Rating Kepentingan");
            popMenuItem_delete.setText("Delete ALL");
            if(!siswa.getValueAt(siswa.getSelectedRow(), 0).equals("")) {

            }
        }else {
            popMenu_siswaRatingKepentingan.setEnabled(false);
        }

    }//GEN-LAST:event_siswaMouseClicked

    private void popMenuItem_showRatingKepentinganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popMenuItem_showRatingKepentinganActionPerformed
        // TODO add your handling code here:
        
        String id = siswa.getValueAt(siswa.getSelectedRow(), 0).toString();
        System.out.println(id);
        
        RatingKepentinganModel ratingKepentinganModel = new RatingKepentinganModel();
        if(ratingKepentinganModel.checkNis(id)) {
            new Rating_Kepentingan(id).setVisible(true);
        }else {
            JOptionPane.showMessageDialog(null, "NIS : "+id+" not found!!!");
        }
        
    }//GEN-LAST:event_popMenuItem_showRatingKepentinganActionPerformed

    private void popMenuItem_addRatingKepentinganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popMenuItem_addRatingKepentinganActionPerformed
        // TODO add your handling code here:
        String id = siswa.getValueAt(siswa.getSelectedRow(), 0).toString();
        System.out.println(id);
        new Add_RatingKepentingan(id).setVisible(true);
    }//GEN-LAST:event_popMenuItem_addRatingKepentinganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data_Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data_Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data_Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data_Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Data_Siswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JScrollPane jsp_siswa;
    private javax.swing.JMenuItem popMenuItem_addRatingKepentingan;
    private javax.swing.JMenuItem popMenuItem_delete;
    private javax.swing.JMenuItem popMenuItem_edit;
    private javax.swing.JMenuItem popMenuItem_settingKriteria;
    private javax.swing.JMenuItem popMenuItem_showRatingKepentingan;
    private javax.swing.JPopupMenu popMenu_siswa;
    private javax.swing.JMenu popMenu_siswaRatingKepentingan;
    public static javax.swing.JTable siswa;
    // End of variables declaration//GEN-END:variables
}
